# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
locale: en-US
title: "IAccessible"
masthead_title: "IAccessible"
#subtitle                 : " All things accessible!"
logo : "/assets/images/cropped - iaccessible_logo_without any text.png"
email: manish@iaccessible.net
description: >- # this means to ignore newlines until "baseurl:"
  Accessibility powered by people with disabilities.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://IAccessible.net" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: __manish
show_excerpts: true
name: &name "IAccessible"
repository: IAccessible/IAccessible.github.io
atom_feed:
  hide : true
# Collections
collections:
  trainings:
    output: true
    permalink: /:collection/:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
# _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      classes: wide
      atom_feed:
        hide : true
# training
  - scope:
      path: ""
      type: trainings
    values:
      layout: single
      sidebar:
        nav: "training"
  
  
author:
  name: Manish
  twitter: __manish
#  picture: https://api.adorable.io/avatars/285/johndoe.png
twitter_username: __manish
github_username: manish10
# logo: /assets/images/cropped - iaccessible_logo_without any text.png
search: true
#search_full_content: true

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-LZ8TB70ZEN"
    anonymize_ip: false # default

# Liquid
liquid:
  error_mode: strict

# Build settings
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

comments:
  provider: "disqus"
  disqus:
    shortname: "IAccessible"
  
# Build settings
# theme: minima
# theme: "minimal-mistakes-jekyll"
# remote_theme: "mmistakes/jekyll-theme-basically-basic" 
remote_theme: "mmistakes/minimal-mistakes@4.22.0"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
#feed:
#  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
# paginate: 5
# paginate_path: /page:num/
include:
  - _pages
  
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
